cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    test_user:
      email: test_user@email.com
      failed_login_attempts: 0
      logged_in: false
      name: Test User
      password: $2b$12$F8YxI31t1szQiUYfj3CaQO6mfAe6v6JSXlxbWwB0IX7t80n5WMU7W
pre-authorized:
  emails:
  - test_user2@email.com
